sonar.organization=jainil2
sonar.projectKey=Jainil2_scopedelta
sonar.sources=src
sonar.tests=src,e2e
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.integration.test.ts,src/**/*.integration.test.tsx
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.integration.test.ts,src/**/*.integration.test.tsx,e2e/**/*.ts
sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/integration/lcov.info
